source 'https://github.com/BuffaloBoyHu/PBComponent.git'
source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!

project 'PBComponentDemo.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PBComponentDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PBComponentDemo

  target 'PBComponentDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PBComponentDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
